# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d990d6810f5063a9cecfde2b5a578f0c"
name = "seedingmanager"
application_url = "https://the8th.cargo.site/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "draft_orders/update" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/create" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_draft_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
