client_id = "d990d6810f5063a9cecfde2b5a578f0c"
name = "x-seeding"
application_url = "https://x-seeding-backend.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "draft_orders/update", "fulfillments/create", "fulfillments/update" ]
  uri = "/webhooks"

[access_scopes]
scopes = "read_inventory,read_products,write_draft_orders,read_draft_orders,read_fulfillments"

[auth]
redirect_urls = [ "https://x-seeding-backend.vercel.app/auth/callback" ]
