client_id = "aeefa5eb5df60d6ed0b4b0727a08b3b2"
name = "x-seeding"
application_url = "https://localhost:3000"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "read_products,read_inventory"

[auth]
redirect_urls = [ "https://localhost:3000/auth/callback" ]
