client_id = "fd3bb73cfc21e2a47db99799ddb620ba"
name = "x-seeding"
application_url = "https://zeedy.xyz"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "draft_orders/update", "fulfillments/create", "fulfillments/update" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/gdpr/customers-data-request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/gdpr/customers-redact"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/gdpr/shop-redact"

[access_scopes]
scopes = "read_inventory,read_products,write_draft_orders,read_draft_orders,read_fulfillments,read_locations"

[auth]
redirect_urls = [ "https://zeedy.xyz/auth/callback" ]
